### ISSUE TITLE
Specification of user response data storage 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-backend#1]
The database that stores information about conference participants. For example, this information is crucial to determine the group assignment of conference participants or store the votes for a given project at the conference. 

### **Task**:

- [x] Define row and column structure of the database. 
- [x] Define queries to maipulate the data.
- [x] Verify data storage strategy with the team.
