### ISSUE TITLE
Implement funding mechanism 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-backend#366]
### Overview 

Create a mechanism that awards funding to participants based on their pluaritly score conditional on a global funding maximum and a global funding minimum. 

### Tasks

- [ ] design funding mechanism  
- [ ] implement the funding mechanism into the backend 
- [ ] expose the funding results through and api endpoint

#### Parameters 

- funding: total available funding 
- plurality_score: score of given project 
- max_funding: global maximum funding for given project 

#### Mechanism Ouline 

1. Rank projects according to the plurality score and assign the requested funding amount until all projects received their requested funding or there is no funding left.  
2. If projects request a funding of more than `max_funding` do not include them in the vote. The `registrationField` must clearly state that they cannot request more than `max_funding` for a single project. 

#### Database Changes 

1. Include `fundingRequest` (optional) column in the `questionOptions` table 
2. Implement a registrationField asking to insert a funding amount as an integer.   

### Alternative Mechanism

1. Create a ranking by the raw plurality score 
3. First 5 projects receive 10% each of the `funding` given that 10% is below `max_funding`
4. Project 6-11  (6 projects) receive 5% each
5. Project 12-19 (8 projects) receive 2.5% each 

The alternative mechanism relies on the assumption that at least 19 projects are up for voting.

The funding mechanism assumes that 19 projects are
